// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjsuyhdlgtmeduqdilec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqc3V5aGRsZ3RtZWR1cWRpbGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzYxNzEsImV4cCI6MjA1ODIxMjE3MX0.3oshyg70gcQj7PNKqH_1V5csoIj6e5MLqcqzWJhlzPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);