// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgdacrkeafssldlxmajm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZGFjcmtlYWZzc2xkbHhtYWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3Mzk4MTEsImV4cCI6MjA1ODMxNTgxMX0.mA3mj9HpoykT0jVmt7IgVHItcHIjiCkw3iI4Ra6urrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);